### ISSUE TITLE
Plugin throws an error after adding JA initialisation Code

### ISSUE THREAD

**Issue by pettinger** [foex-open-source/fos-splitter#5]
After adding 
`function(options) {
    console.log('options',options);
    return options; 
};`
the plugin throws a js error `Uncaught SyntaxError: missing ) after argument list` 
Code snippet from console like that:
`(function(){FOS.splitter({
  "regionId":"Splitter"
 ,"orientation":"horizontal"
 ,"direction":"end"
 ,"positionCode":"0"
 ,"minSize":60
 ,"heightFunction":function(){ return $(window).height() - $('#t_Header').height(); }
 ,"persistStatePref":false
 ,"persistStateLocal":false
 ,"continuousResize":false
 ,"canCollapse":true
 ,"dragCollapse":true
 ,"containsIframe":false
 ,"lazyRender":true
 ,"resizeJetCharts":false
 ,"keyStepSize":10
 ,"titleCollapse":"Ausblenden"
 ,"titleRestore":"Wiederherstellen"
 ,"changeFunction":function(){}
 ,"paddingFirst":16
 ,"paddingSecond":16
}
, function(options) {
    console.log('options',options);
    return options; 
};);})();`

**Comment by foex-open-source** [comment]
You have to remove the semicolon (";") at the end.
```
function(options) {
     console.log('options',options);
      return options; 
}

**Comment by pettinger** [comment]
Great. Thanks
